# Generated by Django 5.1.7 on 2025-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cat Food', 'Cat Food'), ('Medicines', 'Medicines'), ('Dog Food', 'Dog Food')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
