# Generated by Django 5.1.7 on 2025-03-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cat Food', 'Cat Food'), ('Medicine', 'Medicine'), ('Dog Food', 'Dog Food')], max_length=20, null=True),
        ),
    ]
