# Generated by Django 5.1.7 on 2025-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0010_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Cat Food', 'Cat Food'), ('Medicine', 'Medicine'), ('Dog Food', 'Dog Food')], max_length=20, null=True),
        ),
    ]
