# Generated by Django 5.1.7 on 2025-04-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0012_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
