# Generated by Django 5.1.7 on 2025-04-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0014_remove_user_created_at_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
