# Generated by Django 5.2 on 2025-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0024_supplier_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
    ]
