# Generated by Django 5.2 on 2025-04-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0025_alter_productsupplier_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='quantity_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petclinic_app.supplier'),
        ),
    ]
