# Generated by Django 5.2 on 2025-04-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0026_alter_productsupplier_quantity_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='quantity_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='quantity_remaining',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic_app.supplier'),
        ),
        migrations.CreateModel(
            name='CreateOrderSupplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic_app.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic_app.supplier')),
            ],
        ),
    ]
