# Generated by Django 5.2 on 2025-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0029_rename_product_productsupplier_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsupplier',
            old_name='product_name',
            new_name='product',
        ),
    ]
