# Generated by Django 5.2 on 2025-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0030_rename_product_name_productsupplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='pending', max_length=20),
        ),
    ]
