# Generated by Django 5.2 on 2025-04-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0031_alter_productsupplier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
