# Generated by Django 5.2 on 2025-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0032_productsupplier_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
