# Generated by Django 5.2 on 2025-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0036_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='movement_threshold',
            field=models.IntegerField(default=100),
        ),
    ]
