# Generated by Django 5.2 on 2025-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0037_stock_movement_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='movement_threshold',
        ),
        migrations.AddField(
            model_name='product',
            name='movement_threshold',
            field=models.IntegerField(default=100),
        ),
    ]
