# Generated by Django 5.2 on 2025-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0038_remove_stock_movement_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
