# Generated by Django 5.2 on 2025-04-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0040_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petclinic_app.productsupplier'),
        ),
    ]
