# Generated by Django 5.2 on 2025-04-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0041_stock_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
