# Generated by Django 5.2 on 2025-05-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0042_productsupplier_delivery_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateOrderSupplier',
        ),
    ]
