# Generated by Django 5.2 on 2025-05-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic_app', '0043_delete_createordersupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
